// Code generated by entc, DO NOT EDIT.

package gamehustlerquest

const (
	// Label holds the string label denoting the gamehustlerquest type in the database.
	Label = "game_hustler_quest"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuest holds the string denoting the quest field in the database.
	FieldQuest = "quest"
	// FieldCompleted holds the string denoting the completed field in the database.
	FieldCompleted = "completed"
	// EdgeHustler holds the string denoting the hustler edge name in mutations.
	EdgeHustler = "hustler"
	// Table holds the table name of the gamehustlerquest in the database.
	Table = "game_hustler_quests"
	// HustlerTable is the table that holds the hustler relation/edge.
	HustlerTable = "game_hustler_quests"
	// HustlerInverseTable is the table name for the GameHustler entity.
	// It exists in this package in order to avoid circular dependency with the "gamehustler" package.
	HustlerInverseTable = "game_hustlers"
	// HustlerColumn is the table column denoting the hustler relation/edge.
	HustlerColumn = "game_hustler_quests"
)

// Columns holds all SQL columns for gamehustlerquest fields.
var Columns = []string{
	FieldID,
	FieldQuest,
	FieldCompleted,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "game_hustler_quests"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"game_hustler_quests",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCompleted holds the default value on creation for the "completed" field.
	DefaultCompleted bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)
