// Code generated by entc, DO NOT EDIT.

package dope

const (
	// Label holds the string label denoting the dope type in the database.
	Label = "dope"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClaimed holds the string denoting the claimed field in the database.
	FieldClaimed = "claimed"
	// FieldOpened holds the string denoting the opened field in the database.
	FieldOpened = "opened"
	// EdgeWallet holds the string denoting the wallet edge name in mutations.
	EdgeWallet = "wallet"
	// EdgeItems holds the string denoting the items edge name in mutations.
	EdgeItems = "items"
	// Table holds the table name of the dope in the database.
	Table = "dopes"
	// WalletTable is the table that holds the wallet relation/edge.
	WalletTable = "dopes"
	// WalletInverseTable is the table name for the Wallet entity.
	// It exists in this package in order to avoid circular dependency with the "wallet" package.
	WalletInverseTable = "wallets"
	// WalletColumn is the table column denoting the wallet relation/edge.
	WalletColumn = "wallet_dopes"
	// ItemsTable is the table that holds the items relation/edge. The primary key declared below.
	ItemsTable = "dope_items"
	// ItemsInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	ItemsInverseTable = "items"
)

// Columns holds all SQL columns for dope fields.
var Columns = []string{
	FieldID,
	FieldClaimed,
	FieldOpened,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "dopes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"wallet_dopes",
}

var (
	// ItemsPrimaryKey and ItemsColumn2 are the table columns denoting the
	// primary key for the items relation (M2M).
	ItemsPrimaryKey = []string{"dope_id", "item_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultClaimed holds the default value on creation for the "claimed" field.
	DefaultClaimed bool
	// DefaultOpened holds the default value on creation for the "opened" field.
	DefaultOpened bool
)
