// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dopedao/dope-monorepo/packages/api/ent/asset"
	"github.com/dopedao/dope-monorepo/packages/api/ent/predicate"
	"github.com/dopedao/dope-monorepo/packages/api/ent/schema"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks    []Hook
	mutation *AssetMutation
}

// Where appends a list predicates to the AssetUpdate builder.
func (au *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetAddress sets the "address" field.
func (au *AssetUpdate) SetAddress(s string) *AssetUpdate {
	au.mutation.SetAddress(s)
	return au
}

// SetSymbol sets the "symbol" field.
func (au *AssetUpdate) SetSymbol(s string) *AssetUpdate {
	au.mutation.SetSymbol(s)
	return au
}

// SetAmount sets the "amount" field.
func (au *AssetUpdate) SetAmount(si schema.BigInt) *AssetUpdate {
	au.mutation.ResetAmount()
	au.mutation.SetAmount(si)
	return au
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (au *AssetUpdate) SetNillableAmount(si *schema.BigInt) *AssetUpdate {
	if si != nil {
		au.SetAmount(*si)
	}
	return au
}

// AddAmount adds si to the "amount" field.
func (au *AssetUpdate) AddAmount(si schema.BigInt) *AssetUpdate {
	au.mutation.AddAmount(si)
	return au
}

// SetAssetID sets the "asset_id" field.
func (au *AssetUpdate) SetAssetID(si schema.BigInt) *AssetUpdate {
	au.mutation.ResetAssetID()
	au.mutation.SetAssetID(si)
	return au
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (au *AssetUpdate) SetNillableAssetID(si *schema.BigInt) *AssetUpdate {
	if si != nil {
		au.SetAssetID(*si)
	}
	return au
}

// AddAssetID adds si to the "asset_id" field.
func (au *AssetUpdate) AddAssetID(si schema.BigInt) *AssetUpdate {
	au.mutation.AddAssetID(si)
	return au
}

// SetDecimals sets the "decimals" field.
func (au *AssetUpdate) SetDecimals(i int) *AssetUpdate {
	au.mutation.ResetDecimals()
	au.mutation.SetDecimals(i)
	return au
}

// AddDecimals adds i to the "decimals" field.
func (au *AssetUpdate) AddDecimals(i int) *AssetUpdate {
	au.mutation.AddDecimals(i)
	return au
}

// Mutation returns the AssetMutation object of the builder.
func (au *AssetUpdate) Mutation() *AssetMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AssetUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(au.hooks) == 0 {
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AssetMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AssetUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AssetUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AssetUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   asset.Table,
			Columns: asset.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: asset.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: asset.FieldAddress,
		})
	}
	if value, ok := au.mutation.Symbol(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: asset.FieldSymbol,
		})
	}
	if value, ok := au.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldAmount,
		})
	}
	if value, ok := au.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldAmount,
		})
	}
	if value, ok := au.mutation.AssetID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldAssetID,
		})
	}
	if value, ok := au.mutation.AddedAssetID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldAssetID,
		})
	}
	if value, ok := au.mutation.Decimals(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldDecimals,
		})
	}
	if value, ok := au.mutation.AddedDecimals(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldDecimals,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetMutation
}

// SetAddress sets the "address" field.
func (auo *AssetUpdateOne) SetAddress(s string) *AssetUpdateOne {
	auo.mutation.SetAddress(s)
	return auo
}

// SetSymbol sets the "symbol" field.
func (auo *AssetUpdateOne) SetSymbol(s string) *AssetUpdateOne {
	auo.mutation.SetSymbol(s)
	return auo
}

// SetAmount sets the "amount" field.
func (auo *AssetUpdateOne) SetAmount(si schema.BigInt) *AssetUpdateOne {
	auo.mutation.ResetAmount()
	auo.mutation.SetAmount(si)
	return auo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (auo *AssetUpdateOne) SetNillableAmount(si *schema.BigInt) *AssetUpdateOne {
	if si != nil {
		auo.SetAmount(*si)
	}
	return auo
}

// AddAmount adds si to the "amount" field.
func (auo *AssetUpdateOne) AddAmount(si schema.BigInt) *AssetUpdateOne {
	auo.mutation.AddAmount(si)
	return auo
}

// SetAssetID sets the "asset_id" field.
func (auo *AssetUpdateOne) SetAssetID(si schema.BigInt) *AssetUpdateOne {
	auo.mutation.ResetAssetID()
	auo.mutation.SetAssetID(si)
	return auo
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (auo *AssetUpdateOne) SetNillableAssetID(si *schema.BigInt) *AssetUpdateOne {
	if si != nil {
		auo.SetAssetID(*si)
	}
	return auo
}

// AddAssetID adds si to the "asset_id" field.
func (auo *AssetUpdateOne) AddAssetID(si schema.BigInt) *AssetUpdateOne {
	auo.mutation.AddAssetID(si)
	return auo
}

// SetDecimals sets the "decimals" field.
func (auo *AssetUpdateOne) SetDecimals(i int) *AssetUpdateOne {
	auo.mutation.ResetDecimals()
	auo.mutation.SetDecimals(i)
	return auo
}

// AddDecimals adds i to the "decimals" field.
func (auo *AssetUpdateOne) AddDecimals(i int) *AssetUpdateOne {
	auo.mutation.AddDecimals(i)
	return auo
}

// Mutation returns the AssetMutation object of the builder.
func (auo *AssetUpdateOne) Mutation() *AssetMutation {
	return auo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Asset entity.
func (auo *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	var (
		err  error
		node *Asset
	)
	if len(auo.hooks) == 0 {
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AssetMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   asset.Table,
			Columns: asset.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: asset.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: asset.FieldAddress,
		})
	}
	if value, ok := auo.mutation.Symbol(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: asset.FieldSymbol,
		})
	}
	if value, ok := auo.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldAmount,
		})
	}
	if value, ok := auo.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldAmount,
		})
	}
	if value, ok := auo.mutation.AssetID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldAssetID,
		})
	}
	if value, ok := auo.mutation.AddedAssetID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldAssetID,
		})
	}
	if value, ok := auo.mutation.Decimals(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldDecimals,
		})
	}
	if value, ok := auo.mutation.AddedDecimals(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: asset.FieldDecimals,
		})
	}
	_node = &Asset{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
