// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dopedao/dope-monorepo/packages/api/ent/dope"
	"github.com/dopedao/dope-monorepo/packages/api/ent/item"
	"github.com/dopedao/dope-monorepo/packages/api/ent/wallet"
)

// DopeCreate is the builder for creating a Dope entity.
type DopeCreate struct {
	config
	mutation *DopeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetClaimed sets the "claimed" field.
func (dc *DopeCreate) SetClaimed(b bool) *DopeCreate {
	dc.mutation.SetClaimed(b)
	return dc
}

// SetNillableClaimed sets the "claimed" field if the given value is not nil.
func (dc *DopeCreate) SetNillableClaimed(b *bool) *DopeCreate {
	if b != nil {
		dc.SetClaimed(*b)
	}
	return dc
}

// SetOpened sets the "opened" field.
func (dc *DopeCreate) SetOpened(b bool) *DopeCreate {
	dc.mutation.SetOpened(b)
	return dc
}

// SetNillableOpened sets the "opened" field if the given value is not nil.
func (dc *DopeCreate) SetNillableOpened(b *bool) *DopeCreate {
	if b != nil {
		dc.SetOpened(*b)
	}
	return dc
}

// SetID sets the "id" field.
func (dc *DopeCreate) SetID(s string) *DopeCreate {
	dc.mutation.SetID(s)
	return dc
}

// SetWalletID sets the "wallet" edge to the Wallet entity by ID.
func (dc *DopeCreate) SetWalletID(id string) *DopeCreate {
	dc.mutation.SetWalletID(id)
	return dc
}

// SetNillableWalletID sets the "wallet" edge to the Wallet entity by ID if the given value is not nil.
func (dc *DopeCreate) SetNillableWalletID(id *string) *DopeCreate {
	if id != nil {
		dc = dc.SetWalletID(*id)
	}
	return dc
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (dc *DopeCreate) SetWallet(w *Wallet) *DopeCreate {
	return dc.SetWalletID(w.ID)
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (dc *DopeCreate) AddItemIDs(ids ...string) *DopeCreate {
	dc.mutation.AddItemIDs(ids...)
	return dc
}

// AddItems adds the "items" edges to the Item entity.
func (dc *DopeCreate) AddItems(i ...*Item) *DopeCreate {
	ids := make([]string, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return dc.AddItemIDs(ids...)
}

// Mutation returns the DopeMutation object of the builder.
func (dc *DopeCreate) Mutation() *DopeMutation {
	return dc.mutation
}

// Save creates the Dope in the database.
func (dc *DopeCreate) Save(ctx context.Context) (*Dope, error) {
	var (
		err  error
		node *Dope
	)
	dc.defaults()
	if len(dc.hooks) == 0 {
		if err = dc.check(); err != nil {
			return nil, err
		}
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DopeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dc.check(); err != nil {
				return nil, err
			}
			dc.mutation = mutation
			if node, err = dc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			if dc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DopeCreate) SaveX(ctx context.Context) *Dope {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DopeCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DopeCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DopeCreate) defaults() {
	if _, ok := dc.mutation.Claimed(); !ok {
		v := dope.DefaultClaimed
		dc.mutation.SetClaimed(v)
	}
	if _, ok := dc.mutation.Opened(); !ok {
		v := dope.DefaultOpened
		dc.mutation.SetOpened(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DopeCreate) check() error {
	if _, ok := dc.mutation.Claimed(); !ok {
		return &ValidationError{Name: "claimed", err: errors.New(`ent: missing required field "claimed"`)}
	}
	if _, ok := dc.mutation.Opened(); !ok {
		return &ValidationError{Name: "opened", err: errors.New(`ent: missing required field "opened"`)}
	}
	return nil
}

func (dc *DopeCreate) sqlSave(ctx context.Context) (*Dope, error) {
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(string)
	}
	return _node, nil
}

func (dc *DopeCreate) createSpec() (*Dope, *sqlgraph.CreateSpec) {
	var (
		_node = &Dope{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: dope.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: dope.FieldID,
			},
		}
	)
	_spec.OnConflict = dc.conflict
	if id, ok := dc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dc.mutation.Claimed(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: dope.FieldClaimed,
		})
		_node.Claimed = value
	}
	if value, ok := dc.mutation.Opened(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: dope.FieldOpened,
		})
		_node.Opened = value
	}
	if nodes := dc.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dope.WalletTable,
			Columns: []string{dope.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: wallet.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.wallet_dopes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dope.ItemsTable,
			Columns: dope.ItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: item.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Dope.Create().
//		SetClaimed(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DopeUpsert) {
//			SetClaimed(v+v).
//		}).
//		Exec(ctx)
//
func (dc *DopeCreate) OnConflict(opts ...sql.ConflictOption) *DopeUpsertOne {
	dc.conflict = opts
	return &DopeUpsertOne{
		create: dc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (dc *DopeCreate) OnConflictColumns(columns ...string) *DopeUpsertOne {
	dc.conflict = append(dc.conflict, sql.ConflictColumns(columns...))
	return &DopeUpsertOne{
		create: dc,
	}
}

type (
	// DopeUpsertOne is the builder for "upsert"-ing
	//  one Dope node.
	DopeUpsertOne struct {
		create *DopeCreate
	}

	// DopeUpsert is the "OnConflict" setter.
	DopeUpsert struct {
		*sql.UpdateSet
	}
)

// SetClaimed sets the "claimed" field.
func (u *DopeUpsert) SetClaimed(v bool) *DopeUpsert {
	u.Set(dope.FieldClaimed, v)
	return u
}

// UpdateClaimed sets the "claimed" field to the value that was provided on create.
func (u *DopeUpsert) UpdateClaimed() *DopeUpsert {
	u.SetExcluded(dope.FieldClaimed)
	return u
}

// SetOpened sets the "opened" field.
func (u *DopeUpsert) SetOpened(v bool) *DopeUpsert {
	u.Set(dope.FieldOpened, v)
	return u
}

// UpdateOpened sets the "opened" field to the value that was provided on create.
func (u *DopeUpsert) UpdateOpened() *DopeUpsert {
	u.SetExcluded(dope.FieldOpened)
	return u
}

// UpdateNewValues updates the fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dope.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *DopeUpsertOne) UpdateNewValues() *DopeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(dope.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Dope.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *DopeUpsertOne) Ignore() *DopeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DopeUpsertOne) DoNothing() *DopeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DopeCreate.OnConflict
// documentation for more info.
func (u *DopeUpsertOne) Update(set func(*DopeUpsert)) *DopeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DopeUpsert{UpdateSet: update})
	}))
	return u
}

// SetClaimed sets the "claimed" field.
func (u *DopeUpsertOne) SetClaimed(v bool) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.SetClaimed(v)
	})
}

// UpdateClaimed sets the "claimed" field to the value that was provided on create.
func (u *DopeUpsertOne) UpdateClaimed() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateClaimed()
	})
}

// SetOpened sets the "opened" field.
func (u *DopeUpsertOne) SetOpened(v bool) *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.SetOpened(v)
	})
}

// UpdateOpened sets the "opened" field to the value that was provided on create.
func (u *DopeUpsertOne) UpdateOpened() *DopeUpsertOne {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateOpened()
	})
}

// Exec executes the query.
func (u *DopeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DopeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DopeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DopeUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DopeUpsertOne.ID is not supported by MySQL driver. Use DopeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DopeUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DopeCreateBulk is the builder for creating many Dope entities in bulk.
type DopeCreateBulk struct {
	config
	builders []*DopeCreate
	conflict []sql.ConflictOption
}

// Save creates the Dope entities in the database.
func (dcb *DopeCreateBulk) Save(ctx context.Context) ([]*Dope, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Dope, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DopeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DopeCreateBulk) SaveX(ctx context.Context) []*Dope {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DopeCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DopeCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Dope.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DopeUpsert) {
//			SetClaimed(v+v).
//		}).
//		Exec(ctx)
//
func (dcb *DopeCreateBulk) OnConflict(opts ...sql.ConflictOption) *DopeUpsertBulk {
	dcb.conflict = opts
	return &DopeUpsertBulk{
		create: dcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (dcb *DopeCreateBulk) OnConflictColumns(columns ...string) *DopeUpsertBulk {
	dcb.conflict = append(dcb.conflict, sql.ConflictColumns(columns...))
	return &DopeUpsertBulk{
		create: dcb,
	}
}

// DopeUpsertBulk is the builder for "upsert"-ing
// a bulk of Dope nodes.
type DopeUpsertBulk struct {
	create *DopeCreateBulk
}

// UpdateNewValues updates the fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dope.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *DopeUpsertBulk) UpdateNewValues() *DopeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(dope.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Dope.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *DopeUpsertBulk) Ignore() *DopeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DopeUpsertBulk) DoNothing() *DopeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DopeCreateBulk.OnConflict
// documentation for more info.
func (u *DopeUpsertBulk) Update(set func(*DopeUpsert)) *DopeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DopeUpsert{UpdateSet: update})
	}))
	return u
}

// SetClaimed sets the "claimed" field.
func (u *DopeUpsertBulk) SetClaimed(v bool) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.SetClaimed(v)
	})
}

// UpdateClaimed sets the "claimed" field to the value that was provided on create.
func (u *DopeUpsertBulk) UpdateClaimed() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateClaimed()
	})
}

// SetOpened sets the "opened" field.
func (u *DopeUpsertBulk) SetOpened(v bool) *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.SetOpened(v)
	})
}

// UpdateOpened sets the "opened" field to the value that was provided on create.
func (u *DopeUpsertBulk) UpdateOpened() *DopeUpsertBulk {
	return u.Update(func(s *DopeUpsert) {
		s.UpdateOpened()
	})
}

// Exec executes the query.
func (u *DopeUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DopeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DopeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DopeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
