// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/dopedao/dope-monorepo/packages/api/ent/item"
	"github.com/dopedao/dope-monorepo/packages/api/ent/schema"
	"github.com/dopedao/dope-monorepo/packages/api/ent/search"
)

// Item is the model entity for the Item schema.
type Item struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type item.Type `json:"type,omitempty"`
	// NamePrefix holds the value of the "name_prefix" field.
	NamePrefix string `json:"name_prefix,omitempty"`
	// NameSuffix holds the value of the "name_suffix" field.
	NameSuffix string `json:"name_suffix,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Suffix holds the value of the "suffix" field.
	Suffix string `json:"suffix,omitempty"`
	// Augmented holds the value of the "augmented" field.
	Augmented bool `json:"augmented,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// Tier holds the value of the "tier" field.
	Tier item.Tier `json:"tier,omitempty"`
	// Greatness holds the value of the "greatness" field.
	Greatness int `json:"greatness,omitempty"`
	// Rles holds the value of the "rles" field.
	Rles schema.RLEs `json:"rles,omitempty"`
	// Svg holds the value of the "svg" field.
	Svg string `json:"svg,omitempty"`
	// Sprite holds the value of the "sprite" field.
	Sprite schema.Sprites `json:"sprite,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ItemQuery when eager-loading is set.
	Edges           ItemEdges `json:"edges"`
	item_derivative *string
}

// ItemEdges holds the relations/edges for other nodes in the graph.
type ItemEdges struct {
	// Wallets holds the value of the wallets edge.
	Wallets []*WalletItems `json:"wallets,omitempty"`
	// Dopes holds the value of the dopes edge.
	Dopes []*Dope `json:"dopes,omitempty"`
	// HustlerWeapons holds the value of the hustler_weapons edge.
	HustlerWeapons []*Hustler `json:"hustler_weapons,omitempty"`
	// HustlerClothes holds the value of the hustler_clothes edge.
	HustlerClothes []*Hustler `json:"hustler_clothes,omitempty"`
	// HustlerVehicles holds the value of the hustler_vehicles edge.
	HustlerVehicles []*Hustler `json:"hustler_vehicles,omitempty"`
	// HustlerWaists holds the value of the hustler_waists edge.
	HustlerWaists []*Hustler `json:"hustler_waists,omitempty"`
	// HustlerFeet holds the value of the hustler_feet edge.
	HustlerFeet []*Hustler `json:"hustler_feet,omitempty"`
	// HustlerHands holds the value of the hustler_hands edge.
	HustlerHands []*Hustler `json:"hustler_hands,omitempty"`
	// HustlerDrugs holds the value of the hustler_drugs edge.
	HustlerDrugs []*Hustler `json:"hustler_drugs,omitempty"`
	// HustlerNecks holds the value of the hustler_necks edge.
	HustlerNecks []*Hustler `json:"hustler_necks,omitempty"`
	// HustlerRings holds the value of the hustler_rings edge.
	HustlerRings []*Hustler `json:"hustler_rings,omitempty"`
	// HustlerAccessories holds the value of the hustler_accessories edge.
	HustlerAccessories []*Hustler `json:"hustler_accessories,omitempty"`
	// Base holds the value of the base edge.
	Base *Item `json:"base,omitempty"`
	// Derivative holds the value of the derivative edge.
	Derivative []*Item `json:"derivative,omitempty"`
	// Index holds the value of the index edge.
	Index *Search `json:"index,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [15]bool
}

// WalletsOrErr returns the Wallets value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) WalletsOrErr() ([]*WalletItems, error) {
	if e.loadedTypes[0] {
		return e.Wallets, nil
	}
	return nil, &NotLoadedError{edge: "wallets"}
}

// DopesOrErr returns the Dopes value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) DopesOrErr() ([]*Dope, error) {
	if e.loadedTypes[1] {
		return e.Dopes, nil
	}
	return nil, &NotLoadedError{edge: "dopes"}
}

// HustlerWeaponsOrErr returns the HustlerWeapons value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerWeaponsOrErr() ([]*Hustler, error) {
	if e.loadedTypes[2] {
		return e.HustlerWeapons, nil
	}
	return nil, &NotLoadedError{edge: "hustler_weapons"}
}

// HustlerClothesOrErr returns the HustlerClothes value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerClothesOrErr() ([]*Hustler, error) {
	if e.loadedTypes[3] {
		return e.HustlerClothes, nil
	}
	return nil, &NotLoadedError{edge: "hustler_clothes"}
}

// HustlerVehiclesOrErr returns the HustlerVehicles value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerVehiclesOrErr() ([]*Hustler, error) {
	if e.loadedTypes[4] {
		return e.HustlerVehicles, nil
	}
	return nil, &NotLoadedError{edge: "hustler_vehicles"}
}

// HustlerWaistsOrErr returns the HustlerWaists value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerWaistsOrErr() ([]*Hustler, error) {
	if e.loadedTypes[5] {
		return e.HustlerWaists, nil
	}
	return nil, &NotLoadedError{edge: "hustler_waists"}
}

// HustlerFeetOrErr returns the HustlerFeet value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerFeetOrErr() ([]*Hustler, error) {
	if e.loadedTypes[6] {
		return e.HustlerFeet, nil
	}
	return nil, &NotLoadedError{edge: "hustler_feet"}
}

// HustlerHandsOrErr returns the HustlerHands value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerHandsOrErr() ([]*Hustler, error) {
	if e.loadedTypes[7] {
		return e.HustlerHands, nil
	}
	return nil, &NotLoadedError{edge: "hustler_hands"}
}

// HustlerDrugsOrErr returns the HustlerDrugs value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerDrugsOrErr() ([]*Hustler, error) {
	if e.loadedTypes[8] {
		return e.HustlerDrugs, nil
	}
	return nil, &NotLoadedError{edge: "hustler_drugs"}
}

// HustlerNecksOrErr returns the HustlerNecks value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerNecksOrErr() ([]*Hustler, error) {
	if e.loadedTypes[9] {
		return e.HustlerNecks, nil
	}
	return nil, &NotLoadedError{edge: "hustler_necks"}
}

// HustlerRingsOrErr returns the HustlerRings value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerRingsOrErr() ([]*Hustler, error) {
	if e.loadedTypes[10] {
		return e.HustlerRings, nil
	}
	return nil, &NotLoadedError{edge: "hustler_rings"}
}

// HustlerAccessoriesOrErr returns the HustlerAccessories value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) HustlerAccessoriesOrErr() ([]*Hustler, error) {
	if e.loadedTypes[11] {
		return e.HustlerAccessories, nil
	}
	return nil, &NotLoadedError{edge: "hustler_accessories"}
}

// BaseOrErr returns the Base value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEdges) BaseOrErr() (*Item, error) {
	if e.loadedTypes[12] {
		if e.Base == nil {
			// The edge base was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: item.Label}
		}
		return e.Base, nil
	}
	return nil, &NotLoadedError{edge: "base"}
}

// DerivativeOrErr returns the Derivative value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) DerivativeOrErr() ([]*Item, error) {
	if e.loadedTypes[13] {
		return e.Derivative, nil
	}
	return nil, &NotLoadedError{edge: "derivative"}
}

// IndexOrErr returns the Index value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEdges) IndexOrErr() (*Search, error) {
	if e.loadedTypes[14] {
		if e.Index == nil {
			// The edge index was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: search.Label}
		}
		return e.Index, nil
	}
	return nil, &NotLoadedError{edge: "index"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Item) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case item.FieldRles, item.FieldSprite:
			values[i] = new([]byte)
		case item.FieldAugmented:
			values[i] = new(sql.NullBool)
		case item.FieldCount, item.FieldGreatness:
			values[i] = new(sql.NullInt64)
		case item.FieldID, item.FieldType, item.FieldNamePrefix, item.FieldNameSuffix, item.FieldName, item.FieldSuffix, item.FieldTier, item.FieldSvg:
			values[i] = new(sql.NullString)
		case item.ForeignKeys[0]: // item_derivative
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Item", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Item fields.
func (i *Item) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case item.FieldID:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[j])
			} else if value.Valid {
				i.ID = value.String
			}
		case item.FieldType:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[j])
			} else if value.Valid {
				i.Type = item.Type(value.String)
			}
		case item.FieldNamePrefix:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_prefix", values[j])
			} else if value.Valid {
				i.NamePrefix = value.String
			}
		case item.FieldNameSuffix:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_suffix", values[j])
			} else if value.Valid {
				i.NameSuffix = value.String
			}
		case item.FieldName:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[j])
			} else if value.Valid {
				i.Name = value.String
			}
		case item.FieldSuffix:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field suffix", values[j])
			} else if value.Valid {
				i.Suffix = value.String
			}
		case item.FieldAugmented:
			if value, ok := values[j].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field augmented", values[j])
			} else if value.Valid {
				i.Augmented = value.Bool
			}
		case item.FieldCount:
			if value, ok := values[j].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[j])
			} else if value.Valid {
				i.Count = int(value.Int64)
			}
		case item.FieldTier:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[j])
			} else if value.Valid {
				i.Tier = item.Tier(value.String)
			}
		case item.FieldGreatness:
			if value, ok := values[j].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field greatness", values[j])
			} else if value.Valid {
				i.Greatness = int(value.Int64)
			}
		case item.FieldRles:
			if value, ok := values[j].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rles", values[j])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &i.Rles); err != nil {
					return fmt.Errorf("unmarshal field rles: %w", err)
				}
			}
		case item.FieldSvg:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field svg", values[j])
			} else if value.Valid {
				i.Svg = value.String
			}
		case item.FieldSprite:
			if value, ok := values[j].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field sprite", values[j])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &i.Sprite); err != nil {
					return fmt.Errorf("unmarshal field sprite: %w", err)
				}
			}
		case item.ForeignKeys[0]:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_derivative", values[j])
			} else if value.Valid {
				i.item_derivative = new(string)
				*i.item_derivative = value.String
			}
		}
	}
	return nil
}

// QueryWallets queries the "wallets" edge of the Item entity.
func (i *Item) QueryWallets() *WalletItemsQuery {
	return (&ItemClient{config: i.config}).QueryWallets(i)
}

// QueryDopes queries the "dopes" edge of the Item entity.
func (i *Item) QueryDopes() *DopeQuery {
	return (&ItemClient{config: i.config}).QueryDopes(i)
}

// QueryHustlerWeapons queries the "hustler_weapons" edge of the Item entity.
func (i *Item) QueryHustlerWeapons() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerWeapons(i)
}

// QueryHustlerClothes queries the "hustler_clothes" edge of the Item entity.
func (i *Item) QueryHustlerClothes() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerClothes(i)
}

// QueryHustlerVehicles queries the "hustler_vehicles" edge of the Item entity.
func (i *Item) QueryHustlerVehicles() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerVehicles(i)
}

// QueryHustlerWaists queries the "hustler_waists" edge of the Item entity.
func (i *Item) QueryHustlerWaists() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerWaists(i)
}

// QueryHustlerFeet queries the "hustler_feet" edge of the Item entity.
func (i *Item) QueryHustlerFeet() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerFeet(i)
}

// QueryHustlerHands queries the "hustler_hands" edge of the Item entity.
func (i *Item) QueryHustlerHands() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerHands(i)
}

// QueryHustlerDrugs queries the "hustler_drugs" edge of the Item entity.
func (i *Item) QueryHustlerDrugs() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerDrugs(i)
}

// QueryHustlerNecks queries the "hustler_necks" edge of the Item entity.
func (i *Item) QueryHustlerNecks() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerNecks(i)
}

// QueryHustlerRings queries the "hustler_rings" edge of the Item entity.
func (i *Item) QueryHustlerRings() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerRings(i)
}

// QueryHustlerAccessories queries the "hustler_accessories" edge of the Item entity.
func (i *Item) QueryHustlerAccessories() *HustlerQuery {
	return (&ItemClient{config: i.config}).QueryHustlerAccessories(i)
}

// QueryBase queries the "base" edge of the Item entity.
func (i *Item) QueryBase() *ItemQuery {
	return (&ItemClient{config: i.config}).QueryBase(i)
}

// QueryDerivative queries the "derivative" edge of the Item entity.
func (i *Item) QueryDerivative() *ItemQuery {
	return (&ItemClient{config: i.config}).QueryDerivative(i)
}

// QueryIndex queries the "index" edge of the Item entity.
func (i *Item) QueryIndex() *SearchQuery {
	return (&ItemClient{config: i.config}).QueryIndex(i)
}

// Update returns a builder for updating this Item.
// Note that you need to call Item.Unwrap() before calling this method if this Item
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Item) Update() *ItemUpdateOne {
	return (&ItemClient{config: i.config}).UpdateOne(i)
}

// Unwrap unwraps the Item entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Item) Unwrap() *Item {
	tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Item is not a transactional entity")
	}
	i.config.driver = tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Item) String() string {
	var builder strings.Builder
	builder.WriteString("Item(")
	builder.WriteString(fmt.Sprintf("id=%v", i.ID))
	builder.WriteString(", type=")
	builder.WriteString(fmt.Sprintf("%v", i.Type))
	builder.WriteString(", name_prefix=")
	builder.WriteString(i.NamePrefix)
	builder.WriteString(", name_suffix=")
	builder.WriteString(i.NameSuffix)
	builder.WriteString(", name=")
	builder.WriteString(i.Name)
	builder.WriteString(", suffix=")
	builder.WriteString(i.Suffix)
	builder.WriteString(", augmented=")
	builder.WriteString(fmt.Sprintf("%v", i.Augmented))
	builder.WriteString(", count=")
	builder.WriteString(fmt.Sprintf("%v", i.Count))
	builder.WriteString(", tier=")
	builder.WriteString(fmt.Sprintf("%v", i.Tier))
	builder.WriteString(", greatness=")
	builder.WriteString(fmt.Sprintf("%v", i.Greatness))
	builder.WriteString(", rles=")
	builder.WriteString(fmt.Sprintf("%v", i.Rles))
	builder.WriteString(", svg=")
	builder.WriteString(i.Svg)
	builder.WriteString(", sprite=")
	builder.WriteString(fmt.Sprintf("%v", i.Sprite))
	builder.WriteByte(')')
	return builder.String()
}

// Items is a parsable slice of Item.
type Items []*Item

func (i Items) config(cfg config) {
	for _i := range i {
		i[_i].config = cfg
	}
}
