// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/dopedao/dope-monorepo/packages/api/ent/schema"
	"github.com/dopedao/dope-monorepo/packages/api/ent/wallet"
)

// Wallet is the model entity for the Wallet schema.
type Wallet struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Paper holds the value of the "paper" field.
	Paper schema.BigInt `json:"paper,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WalletQuery when eager-loading is set.
	Edges WalletEdges `json:"edges"`
}

// WalletEdges holds the relations/edges for other nodes in the graph.
type WalletEdges struct {
	// Dopes holds the value of the dopes edge.
	Dopes []*Dope `json:"dopes,omitempty"`
	// Items holds the value of the items edge.
	Items []*WalletItems `json:"items,omitempty"`
	// Hustlers holds the value of the hustlers edge.
	Hustlers []*Hustler `json:"hustlers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DopesOrErr returns the Dopes value or an error if the edge
// was not loaded in eager-loading.
func (e WalletEdges) DopesOrErr() ([]*Dope, error) {
	if e.loadedTypes[0] {
		return e.Dopes, nil
	}
	return nil, &NotLoadedError{edge: "dopes"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e WalletEdges) ItemsOrErr() ([]*WalletItems, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// HustlersOrErr returns the Hustlers value or an error if the edge
// was not loaded in eager-loading.
func (e WalletEdges) HustlersOrErr() ([]*Hustler, error) {
	if e.loadedTypes[2] {
		return e.Hustlers, nil
	}
	return nil, &NotLoadedError{edge: "hustlers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Wallet) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case wallet.FieldPaper:
			values[i] = new(schema.BigInt)
		case wallet.FieldID:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Wallet", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Wallet fields.
func (w *Wallet) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wallet.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				w.ID = value.String
			}
		case wallet.FieldPaper:
			if value, ok := values[i].(*schema.BigInt); !ok {
				return fmt.Errorf("unexpected type %T for field paper", values[i])
			} else if value != nil {
				w.Paper = *value
			}
		}
	}
	return nil
}

// QueryDopes queries the "dopes" edge of the Wallet entity.
func (w *Wallet) QueryDopes() *DopeQuery {
	return (&WalletClient{config: w.config}).QueryDopes(w)
}

// QueryItems queries the "items" edge of the Wallet entity.
func (w *Wallet) QueryItems() *WalletItemsQuery {
	return (&WalletClient{config: w.config}).QueryItems(w)
}

// QueryHustlers queries the "hustlers" edge of the Wallet entity.
func (w *Wallet) QueryHustlers() *HustlerQuery {
	return (&WalletClient{config: w.config}).QueryHustlers(w)
}

// Update returns a builder for updating this Wallet.
// Note that you need to call Wallet.Unwrap() before calling this method if this Wallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (w *Wallet) Update() *WalletUpdateOne {
	return (&WalletClient{config: w.config}).UpdateOne(w)
}

// Unwrap unwraps the Wallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (w *Wallet) Unwrap() *Wallet {
	tx, ok := w.config.driver.(*txDriver)
	if !ok {
		panic("ent: Wallet is not a transactional entity")
	}
	w.config.driver = tx.drv
	return w
}

// String implements the fmt.Stringer.
func (w *Wallet) String() string {
	var builder strings.Builder
	builder.WriteString("Wallet(")
	builder.WriteString(fmt.Sprintf("id=%v", w.ID))
	builder.WriteString(", paper=")
	builder.WriteString(fmt.Sprintf("%v", w.Paper))
	builder.WriteByte(')')
	return builder.String()
}

// Wallets is a parsable slice of Wallet.
type Wallets []*Wallet

func (w Wallets) config(cfg config) {
	for _i := range w {
		w[_i].config = cfg
	}
}
