// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/item"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/predicate"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/wallet"
	"github.com/dopedao/dope-monorepo/packages/api/internal/ent/walletitems"
)

// WalletItemsQuery is the builder for querying WalletItems entities.
type WalletItemsQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.WalletItems
	// eager-loading edges.
	withWallet *WalletQuery
	withItem   *ItemQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WalletItemsQuery builder.
func (wiq *WalletItemsQuery) Where(ps ...predicate.WalletItems) *WalletItemsQuery {
	wiq.predicates = append(wiq.predicates, ps...)
	return wiq
}

// Limit adds a limit step to the query.
func (wiq *WalletItemsQuery) Limit(limit int) *WalletItemsQuery {
	wiq.limit = &limit
	return wiq
}

// Offset adds an offset step to the query.
func (wiq *WalletItemsQuery) Offset(offset int) *WalletItemsQuery {
	wiq.offset = &offset
	return wiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wiq *WalletItemsQuery) Unique(unique bool) *WalletItemsQuery {
	wiq.unique = &unique
	return wiq
}

// Order adds an order step to the query.
func (wiq *WalletItemsQuery) Order(o ...OrderFunc) *WalletItemsQuery {
	wiq.order = append(wiq.order, o...)
	return wiq
}

// QueryWallet chains the current query on the "wallet" edge.
func (wiq *WalletItemsQuery) QueryWallet() *WalletQuery {
	query := &WalletQuery{config: wiq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(walletitems.Table, walletitems.FieldID, selector),
			sqlgraph.To(wallet.Table, wallet.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, walletitems.WalletTable, walletitems.WalletColumn),
		)
		fromU = sqlgraph.SetNeighbors(wiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryItem chains the current query on the "item" edge.
func (wiq *WalletItemsQuery) QueryItem() *ItemQuery {
	query := &ItemQuery{config: wiq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(walletitems.Table, walletitems.FieldID, selector),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, walletitems.ItemTable, walletitems.ItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(wiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WalletItems entity from the query.
// Returns a *NotFoundError when no WalletItems was found.
func (wiq *WalletItemsQuery) First(ctx context.Context) (*WalletItems, error) {
	nodes, err := wiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{walletitems.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wiq *WalletItemsQuery) FirstX(ctx context.Context) *WalletItems {
	node, err := wiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WalletItems ID from the query.
// Returns a *NotFoundError when no WalletItems ID was found.
func (wiq *WalletItemsQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = wiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{walletitems.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wiq *WalletItemsQuery) FirstIDX(ctx context.Context) string {
	id, err := wiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WalletItems entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WalletItems entity is found.
// Returns a *NotFoundError when no WalletItems entities are found.
func (wiq *WalletItemsQuery) Only(ctx context.Context) (*WalletItems, error) {
	nodes, err := wiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{walletitems.Label}
	default:
		return nil, &NotSingularError{walletitems.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wiq *WalletItemsQuery) OnlyX(ctx context.Context) *WalletItems {
	node, err := wiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WalletItems ID in the query.
// Returns a *NotSingularError when more than one WalletItems ID is found.
// Returns a *NotFoundError when no entities are found.
func (wiq *WalletItemsQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = wiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{walletitems.Label}
	default:
		err = &NotSingularError{walletitems.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wiq *WalletItemsQuery) OnlyIDX(ctx context.Context) string {
	id, err := wiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WalletItemsSlice.
func (wiq *WalletItemsQuery) All(ctx context.Context) ([]*WalletItems, error) {
	if err := wiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return wiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (wiq *WalletItemsQuery) AllX(ctx context.Context) []*WalletItems {
	nodes, err := wiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WalletItems IDs.
func (wiq *WalletItemsQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := wiq.Select(walletitems.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wiq *WalletItemsQuery) IDsX(ctx context.Context) []string {
	ids, err := wiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wiq *WalletItemsQuery) Count(ctx context.Context) (int, error) {
	if err := wiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return wiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (wiq *WalletItemsQuery) CountX(ctx context.Context) int {
	count, err := wiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wiq *WalletItemsQuery) Exist(ctx context.Context) (bool, error) {
	if err := wiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return wiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (wiq *WalletItemsQuery) ExistX(ctx context.Context) bool {
	exist, err := wiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WalletItemsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wiq *WalletItemsQuery) Clone() *WalletItemsQuery {
	if wiq == nil {
		return nil
	}
	return &WalletItemsQuery{
		config:     wiq.config,
		limit:      wiq.limit,
		offset:     wiq.offset,
		order:      append([]OrderFunc{}, wiq.order...),
		predicates: append([]predicate.WalletItems{}, wiq.predicates...),
		withWallet: wiq.withWallet.Clone(),
		withItem:   wiq.withItem.Clone(),
		// clone intermediate query.
		sql:    wiq.sql.Clone(),
		path:   wiq.path,
		unique: wiq.unique,
	}
}

// WithWallet tells the query-builder to eager-load the nodes that are connected to
// the "wallet" edge. The optional arguments are used to configure the query builder of the edge.
func (wiq *WalletItemsQuery) WithWallet(opts ...func(*WalletQuery)) *WalletItemsQuery {
	query := &WalletQuery{config: wiq.config}
	for _, opt := range opts {
		opt(query)
	}
	wiq.withWallet = query
	return wiq
}

// WithItem tells the query-builder to eager-load the nodes that are connected to
// the "item" edge. The optional arguments are used to configure the query builder of the edge.
func (wiq *WalletItemsQuery) WithItem(opts ...func(*ItemQuery)) *WalletItemsQuery {
	query := &ItemQuery{config: wiq.config}
	for _, opt := range opts {
		opt(query)
	}
	wiq.withItem = query
	return wiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Balance schema.BigInt `json:"balance,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WalletItems.Query().
//		GroupBy(walletitems.FieldBalance).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (wiq *WalletItemsQuery) GroupBy(field string, fields ...string) *WalletItemsGroupBy {
	group := &WalletItemsGroupBy{config: wiq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := wiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return wiq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Balance schema.BigInt `json:"balance,omitempty"`
//	}
//
//	client.WalletItems.Query().
//		Select(walletitems.FieldBalance).
//		Scan(ctx, &v)
//
func (wiq *WalletItemsQuery) Select(fields ...string) *WalletItemsSelect {
	wiq.fields = append(wiq.fields, fields...)
	return &WalletItemsSelect{WalletItemsQuery: wiq}
}

func (wiq *WalletItemsQuery) prepareQuery(ctx context.Context) error {
	for _, f := range wiq.fields {
		if !walletitems.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wiq.path != nil {
		prev, err := wiq.path(ctx)
		if err != nil {
			return err
		}
		wiq.sql = prev
	}
	return nil
}

func (wiq *WalletItemsQuery) sqlAll(ctx context.Context) ([]*WalletItems, error) {
	var (
		nodes       = []*WalletItems{}
		withFKs     = wiq.withFKs
		_spec       = wiq.querySpec()
		loadedTypes = [2]bool{
			wiq.withWallet != nil,
			wiq.withItem != nil,
		}
	)
	if wiq.withWallet != nil || wiq.withItem != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, walletitems.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &WalletItems{config: wiq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, wiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := wiq.withWallet; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*WalletItems)
		for i := range nodes {
			if nodes[i].wallet_items == nil {
				continue
			}
			fk := *nodes[i].wallet_items
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(wallet.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "wallet_items" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Wallet = n
			}
		}
	}

	if query := wiq.withItem; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*WalletItems)
		for i := range nodes {
			if nodes[i].item_wallets == nil {
				continue
			}
			fk := *nodes[i].item_wallets
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(item.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "item_wallets" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Item = n
			}
		}
	}

	return nodes, nil
}

func (wiq *WalletItemsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wiq.querySpec()
	_spec.Node.Columns = wiq.fields
	if len(wiq.fields) > 0 {
		_spec.Unique = wiq.unique != nil && *wiq.unique
	}
	return sqlgraph.CountNodes(ctx, wiq.driver, _spec)
}

func (wiq *WalletItemsQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := wiq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (wiq *WalletItemsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   walletitems.Table,
			Columns: walletitems.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: walletitems.FieldID,
			},
		},
		From:   wiq.sql,
		Unique: true,
	}
	if unique := wiq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := wiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, walletitems.FieldID)
		for i := range fields {
			if fields[i] != walletitems.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wiq *WalletItemsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wiq.driver.Dialect())
	t1 := builder.Table(walletitems.Table)
	columns := wiq.fields
	if len(columns) == 0 {
		columns = walletitems.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wiq.sql != nil {
		selector = wiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wiq.unique != nil && *wiq.unique {
		selector.Distinct()
	}
	for _, p := range wiq.predicates {
		p(selector)
	}
	for _, p := range wiq.order {
		p(selector)
	}
	if offset := wiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WalletItemsGroupBy is the group-by builder for WalletItems entities.
type WalletItemsGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wigb *WalletItemsGroupBy) Aggregate(fns ...AggregateFunc) *WalletItemsGroupBy {
	wigb.fns = append(wigb.fns, fns...)
	return wigb
}

// Scan applies the group-by query and scans the result into the given value.
func (wigb *WalletItemsGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := wigb.path(ctx)
	if err != nil {
		return err
	}
	wigb.sql = query
	return wigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wigb *WalletItemsGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := wigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (wigb *WalletItemsGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(wigb.fields) > 1 {
		return nil, errors.New("ent: WalletItemsGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := wigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wigb *WalletItemsGroupBy) StringsX(ctx context.Context) []string {
	v, err := wigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wigb *WalletItemsGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{walletitems.Label}
	default:
		err = fmt.Errorf("ent: WalletItemsGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wigb *WalletItemsGroupBy) StringX(ctx context.Context) string {
	v, err := wigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (wigb *WalletItemsGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(wigb.fields) > 1 {
		return nil, errors.New("ent: WalletItemsGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := wigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wigb *WalletItemsGroupBy) IntsX(ctx context.Context) []int {
	v, err := wigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wigb *WalletItemsGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{walletitems.Label}
	default:
		err = fmt.Errorf("ent: WalletItemsGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wigb *WalletItemsGroupBy) IntX(ctx context.Context) int {
	v, err := wigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (wigb *WalletItemsGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(wigb.fields) > 1 {
		return nil, errors.New("ent: WalletItemsGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := wigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wigb *WalletItemsGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := wigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wigb *WalletItemsGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{walletitems.Label}
	default:
		err = fmt.Errorf("ent: WalletItemsGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wigb *WalletItemsGroupBy) Float64X(ctx context.Context) float64 {
	v, err := wigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (wigb *WalletItemsGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(wigb.fields) > 1 {
		return nil, errors.New("ent: WalletItemsGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := wigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wigb *WalletItemsGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := wigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wigb *WalletItemsGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{walletitems.Label}
	default:
		err = fmt.Errorf("ent: WalletItemsGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wigb *WalletItemsGroupBy) BoolX(ctx context.Context) bool {
	v, err := wigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wigb *WalletItemsGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range wigb.fields {
		if !walletitems.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := wigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (wigb *WalletItemsGroupBy) sqlQuery() *sql.Selector {
	selector := wigb.sql.Select()
	aggregation := make([]string, 0, len(wigb.fns))
	for _, fn := range wigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(wigb.fields)+len(wigb.fns))
		for _, f := range wigb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(wigb.fields...)...)
}

// WalletItemsSelect is the builder for selecting fields of WalletItems entities.
type WalletItemsSelect struct {
	*WalletItemsQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (wis *WalletItemsSelect) Scan(ctx context.Context, v interface{}) error {
	if err := wis.prepareQuery(ctx); err != nil {
		return err
	}
	wis.sql = wis.WalletItemsQuery.sqlQuery(ctx)
	return wis.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wis *WalletItemsSelect) ScanX(ctx context.Context, v interface{}) {
	if err := wis.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (wis *WalletItemsSelect) Strings(ctx context.Context) ([]string, error) {
	if len(wis.fields) > 1 {
		return nil, errors.New("ent: WalletItemsSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := wis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wis *WalletItemsSelect) StringsX(ctx context.Context) []string {
	v, err := wis.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (wis *WalletItemsSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wis.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{walletitems.Label}
	default:
		err = fmt.Errorf("ent: WalletItemsSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wis *WalletItemsSelect) StringX(ctx context.Context) string {
	v, err := wis.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (wis *WalletItemsSelect) Ints(ctx context.Context) ([]int, error) {
	if len(wis.fields) > 1 {
		return nil, errors.New("ent: WalletItemsSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := wis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wis *WalletItemsSelect) IntsX(ctx context.Context) []int {
	v, err := wis.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (wis *WalletItemsSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wis.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{walletitems.Label}
	default:
		err = fmt.Errorf("ent: WalletItemsSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wis *WalletItemsSelect) IntX(ctx context.Context) int {
	v, err := wis.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (wis *WalletItemsSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(wis.fields) > 1 {
		return nil, errors.New("ent: WalletItemsSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := wis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wis *WalletItemsSelect) Float64sX(ctx context.Context) []float64 {
	v, err := wis.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (wis *WalletItemsSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wis.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{walletitems.Label}
	default:
		err = fmt.Errorf("ent: WalletItemsSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wis *WalletItemsSelect) Float64X(ctx context.Context) float64 {
	v, err := wis.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (wis *WalletItemsSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(wis.fields) > 1 {
		return nil, errors.New("ent: WalletItemsSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := wis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wis *WalletItemsSelect) BoolsX(ctx context.Context) []bool {
	v, err := wis.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (wis *WalletItemsSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wis.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{walletitems.Label}
	default:
		err = fmt.Errorf("ent: WalletItemsSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wis *WalletItemsSelect) BoolX(ctx context.Context) bool {
	v, err := wis.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wis *WalletItemsSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := wis.sql.Query()
	if err := wis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
