// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Amount is the predicate function for amount builders.
type Amount func(*sql.Selector)

// BodyPart is the predicate function for bodypart builders.
type BodyPart func(*sql.Selector)

// Dope is the predicate function for dope builders.
type Dope func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// GameHustler is the predicate function for gamehustler builders.
type GameHustler func(*sql.Selector)

// GameHustlerItem is the predicate function for gamehustleritem builders.
type GameHustlerItem func(*sql.Selector)

// GameHustlerQuest is the predicate function for gamehustlerquest builders.
type GameHustlerQuest func(*sql.Selector)

// GameHustlerRelation is the predicate function for gamehustlerrelation builders.
type GameHustlerRelation func(*sql.Selector)

// Hustler is the predicate function for hustler builders.
type Hustler func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Listing is the predicate function for listing builders.
type Listing func(*sql.Selector)

// Search is the predicate function for search builders.
type Search func(*sql.Selector)

// SyncState is the predicate function for syncstate builders.
type SyncState func(*sql.Selector)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)

// WalletItems is the predicate function for walletitems builders.
type WalletItems func(*sql.Selector)
