// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BodyPartsColumns holds the columns for the "body_parts" table.
	BodyPartsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"body", "hair", "beard"}},
		{Name: "sex", Type: field.TypeEnum, Enums: []string{"male", "female"}},
		{Name: "rle", Type: field.TypeString},
		{Name: "hustler_bodyparts", Type: field.TypeString, Nullable: true},
	}
	// BodyPartsTable holds the schema information for the "body_parts" table.
	BodyPartsTable = &schema.Table{
		Name:       "body_parts",
		Columns:    BodyPartsColumns,
		PrimaryKey: []*schema.Column{BodyPartsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "body_parts_hustlers_bodyparts",
				Columns:    []*schema.Column{BodyPartsColumns[4]},
				RefColumns: []*schema.Column{HustlersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DopesColumns holds the columns for the "dopes" table.
	DopesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "claimed", Type: field.TypeBool, Default: false},
		{Name: "opened", Type: field.TypeBool, Default: false},
		{Name: "wallet_dopes", Type: field.TypeString, Nullable: true},
	}
	// DopesTable holds the schema information for the "dopes" table.
	DopesTable = &schema.Table{
		Name:       "dopes",
		Columns:    DopesColumns,
		PrimaryKey: []*schema.Column{DopesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "dopes_wallets_dopes",
				Columns:    []*schema.Column{DopesColumns[3]},
				RefColumns: []*schema.Column{WalletsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// HustlersColumns holds the columns for the "hustlers" table.
	HustlersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"original_gangsta", "regular"}},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "background", Type: field.TypeString, Nullable: true},
		{Name: "age", Type: field.TypeUint64},
		{Name: "sex", Type: field.TypeEnum, Nullable: true, Enums: []string{"male", "female"}},
		{Name: "wallet_hustlers", Type: field.TypeString, Nullable: true},
	}
	// HustlersTable holds the schema information for the "hustlers" table.
	HustlersTable = &schema.Table{
		Name:       "hustlers",
		Columns:    HustlersColumns,
		PrimaryKey: []*schema.Column{HustlersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hustlers_wallets_hustlers",
				Columns:    []*schema.Column{HustlersColumns[8]},
				RefColumns: []*schema.Column{WalletsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"weapon", "clothes", "vehicle", "waist", "foot", "hand", "drugs", "neck", "ring", "accessory"}},
		{Name: "name_prefix", Type: field.TypeString, Nullable: true},
		{Name: "name_suffix", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "suffix", Type: field.TypeString, Nullable: true},
		{Name: "augmented", Type: field.TypeBool, Nullable: true},
		{Name: "rles", Type: field.TypeJSON, Nullable: true},
		{Name: "svg", Type: field.TypeString, Nullable: true},
		{Name: "hustler_items", Type: field.TypeString, Nullable: true},
		{Name: "item_derivative", Type: field.TypeString, Nullable: true},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "items_hustlers_items",
				Columns:    []*schema.Column{ItemsColumns[9]},
				RefColumns: []*schema.Column{HustlersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "items_items_derivative",
				Columns:    []*schema.Column{ItemsColumns[10]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SyncStatesColumns holds the columns for the "sync_states" table.
	SyncStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "start_block", Type: field.TypeUint64},
	}
	// SyncStatesTable holds the schema information for the "sync_states" table.
	SyncStatesTable = &schema.Table{
		Name:       "sync_states",
		Columns:    SyncStatesColumns,
		PrimaryKey: []*schema.Column{SyncStatesColumns[0]},
	}
	// WalletsColumns holds the columns for the "wallets" table.
	WalletsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "paper", Type: field.TypeInt, SchemaType: map[string]string{"postgres": "numeric"}},
	}
	// WalletsTable holds the schema information for the "wallets" table.
	WalletsTable = &schema.Table{
		Name:       "wallets",
		Columns:    WalletsColumns,
		PrimaryKey: []*schema.Column{WalletsColumns[0]},
	}
	// WalletItemsColumns holds the columns for the "wallet_items" table.
	WalletItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "balance", Type: field.TypeInt, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "item_wallets", Type: field.TypeString, Nullable: true},
		{Name: "wallet_items", Type: field.TypeString, Nullable: true},
	}
	// WalletItemsTable holds the schema information for the "wallet_items" table.
	WalletItemsTable = &schema.Table{
		Name:       "wallet_items",
		Columns:    WalletItemsColumns,
		PrimaryKey: []*schema.Column{WalletItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wallet_items_items_wallets",
				Columns:    []*schema.Column{WalletItemsColumns[2]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "wallet_items_wallets_items",
				Columns:    []*schema.Column{WalletItemsColumns[3]},
				RefColumns: []*schema.Column{WalletsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DopeItemsColumns holds the columns for the "dope_items" table.
	DopeItemsColumns = []*schema.Column{
		{Name: "dope_id", Type: field.TypeString},
		{Name: "item_id", Type: field.TypeString},
	}
	// DopeItemsTable holds the schema information for the "dope_items" table.
	DopeItemsTable = &schema.Table{
		Name:       "dope_items",
		Columns:    DopeItemsColumns,
		PrimaryKey: []*schema.Column{DopeItemsColumns[0], DopeItemsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "dope_items_dope_id",
				Columns:    []*schema.Column{DopeItemsColumns[0]},
				RefColumns: []*schema.Column{DopesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "dope_items_item_id",
				Columns:    []*schema.Column{DopeItemsColumns[1]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BodyPartsTable,
		DopesTable,
		HustlersTable,
		ItemsTable,
		SyncStatesTable,
		WalletsTable,
		WalletItemsTable,
		DopeItemsTable,
	}
)

func init() {
	BodyPartsTable.ForeignKeys[0].RefTable = HustlersTable
	DopesTable.ForeignKeys[0].RefTable = WalletsTable
	HustlersTable.ForeignKeys[0].RefTable = WalletsTable
	ItemsTable.ForeignKeys[0].RefTable = HustlersTable
	ItemsTable.ForeignKeys[1].RefTable = ItemsTable
	WalletItemsTable.ForeignKeys[0].RefTable = ItemsTable
	WalletItemsTable.ForeignKeys[1].RefTable = WalletsTable
	DopeItemsTable.ForeignKeys[0].RefTable = DopesTable
	DopeItemsTable.ForeignKeys[1].RefTable = ItemsTable
}
