// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DopesColumns holds the columns for the "dopes" table.
	DopesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "clothes", Type: field.TypeString},
		{Name: "foot", Type: field.TypeString},
		{Name: "hand", Type: field.TypeString},
		{Name: "neck", Type: field.TypeString},
		{Name: "ring", Type: field.TypeString},
		{Name: "waist", Type: field.TypeString},
		{Name: "weapon", Type: field.TypeString},
		{Name: "drugs", Type: field.TypeString},
		{Name: "vehicle", Type: field.TypeString},
		{Name: "claimed", Type: field.TypeBool},
		{Name: "opened", Type: field.TypeBool},
		{Name: "wallet_dopes", Type: field.TypeString, Nullable: true},
	}
	// DopesTable holds the schema information for the "dopes" table.
	DopesTable = &schema.Table{
		Name:       "dopes",
		Columns:    DopesColumns,
		PrimaryKey: []*schema.Column{DopesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "dopes_wallets_dopes",
				Columns:    []*schema.Column{DopesColumns[12]},
				RefColumns: []*schema.Column{WalletsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// WalletsColumns holds the columns for the "wallets" table.
	WalletsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "paper", Type: field.TypeInt, SchemaType: map[string]string{"postgres": "numeric"}},
	}
	// WalletsTable holds the schema information for the "wallets" table.
	WalletsTable = &schema.Table{
		Name:       "wallets",
		Columns:    WalletsColumns,
		PrimaryKey: []*schema.Column{WalletsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DopesTable,
		WalletsTable,
	}
)

func init() {
	DopesTable.ForeignKeys[0].RefTable = WalletsTable
}
