// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Dope is the predicate function for dope builders.
type Dope func(*sql.Selector)

// Hustler is the predicate function for hustler builders.
type Hustler func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)
