// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/dopedao/dope-monorepo/packages/api/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
