// Code generated by github.com/withtally/synceth, DO NOT EDIT.

package bindings

import (
	"context"
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	"github.com/dopedao/dope-monorepo/packages/api/ent"
)

type SwapMeetProcessor interface {
	Setup(address common.Address, eth interface {
		ethereum.ChainReader
		ethereum.ChainStateReader
		ethereum.TransactionReader
		bind.ContractBackend
	}) error
	Initialize(ctx context.Context, start uint64, tx *ent.Tx) error

	ProcessApprovalForAll(ctx context.Context, e SwapMeetApprovalForAll) (func(tx *ent.Tx) error, error)

	ProcessOwnershipTransferred(ctx context.Context, e SwapMeetOwnershipTransferred) (func(tx *ent.Tx) error, error)

	ProcessSetRle(ctx context.Context, e SwapMeetSetRle) (func(tx *ent.Tx) error, error)

	ProcessTransferBatch(ctx context.Context, e SwapMeetTransferBatch) (func(tx *ent.Tx) error, error)

	ProcessTransferSingle(ctx context.Context, e SwapMeetTransferSingle) (func(tx *ent.Tx) error, error)

	ProcessURI(ctx context.Context, e SwapMeetURI) (func(tx *ent.Tx) error, error)

	mustEmbedBaseSwapMeetProcessor()
}

type BaseSwapMeetProcessor struct {
	Address  common.Address
	ABI      abi.ABI
	Contract *SwapMeet
	Eth      interface {
		ethereum.ChainReader
		ethereum.ChainStateReader
		ethereum.TransactionReader
		bind.ContractBackend
	}
}

func (h *BaseSwapMeetProcessor) Setup(address common.Address, eth interface {
	ethereum.ChainReader
	ethereum.ChainStateReader
	ethereum.TransactionReader
	bind.ContractBackend
}) error {
	contract, err := NewSwapMeet(address, eth)
	if err != nil {
		return fmt.Errorf("new SwapMeet: %w", err)
	}

	abi, err := abi.JSON(strings.NewReader(string(SwapMeetABI)))
	if err != nil {
		return fmt.Errorf("parsing SwapMeet abi: %w", err)
	}

	h.Address = address
	h.ABI = abi
	h.Contract = contract
	h.Eth = eth
	return nil
}

func (h *BaseSwapMeetProcessor) ProcessElement(p interface{}) func(context.Context, types.Log) (func(*ent.Tx) error, error) {
	return func(ctx context.Context, vLog types.Log) (func(*ent.Tx) error, error) {
		switch vLog.Topics[0].Hex() {

		case h.ABI.Events["ApprovalForAll"].ID.Hex():
			e := SwapMeetApprovalForAll{}
			if err := h.UnpackLog(&e, "ApprovalForAll", vLog); err != nil {
				return nil, fmt.Errorf("unpacking ApprovalForAll: %w", err)
			}

			e.Raw = vLog
			cb, err := p.(SwapMeetProcessor).ProcessApprovalForAll(ctx, e)
			if err != nil {
				return nil, fmt.Errorf("processing ApprovalForAll: %w", err)
			}

			return cb, nil

		case h.ABI.Events["OwnershipTransferred"].ID.Hex():
			e := SwapMeetOwnershipTransferred{}
			if err := h.UnpackLog(&e, "OwnershipTransferred", vLog); err != nil {
				return nil, fmt.Errorf("unpacking OwnershipTransferred: %w", err)
			}

			e.Raw = vLog
			cb, err := p.(SwapMeetProcessor).ProcessOwnershipTransferred(ctx, e)
			if err != nil {
				return nil, fmt.Errorf("processing OwnershipTransferred: %w", err)
			}

			return cb, nil

		case h.ABI.Events["SetRle"].ID.Hex():
			e := SwapMeetSetRle{}
			if err := h.UnpackLog(&e, "SetRle", vLog); err != nil {
				return nil, fmt.Errorf("unpacking SetRle: %w", err)
			}

			e.Raw = vLog
			cb, err := p.(SwapMeetProcessor).ProcessSetRle(ctx, e)
			if err != nil {
				return nil, fmt.Errorf("processing SetRle: %w", err)
			}

			return cb, nil

		case h.ABI.Events["TransferBatch"].ID.Hex():
			e := SwapMeetTransferBatch{}
			if err := h.UnpackLog(&e, "TransferBatch", vLog); err != nil {
				return nil, fmt.Errorf("unpacking TransferBatch: %w", err)
			}

			e.Raw = vLog
			cb, err := p.(SwapMeetProcessor).ProcessTransferBatch(ctx, e)
			if err != nil {
				return nil, fmt.Errorf("processing TransferBatch: %w", err)
			}

			return cb, nil

		case h.ABI.Events["TransferSingle"].ID.Hex():
			e := SwapMeetTransferSingle{}
			if err := h.UnpackLog(&e, "TransferSingle", vLog); err != nil {
				return nil, fmt.Errorf("unpacking TransferSingle: %w", err)
			}

			e.Raw = vLog
			cb, err := p.(SwapMeetProcessor).ProcessTransferSingle(ctx, e)
			if err != nil {
				return nil, fmt.Errorf("processing TransferSingle: %w", err)
			}

			return cb, nil

		case h.ABI.Events["URI"].ID.Hex():
			e := SwapMeetURI{}
			if err := h.UnpackLog(&e, "URI", vLog); err != nil {
				return nil, fmt.Errorf("unpacking URI: %w", err)
			}

			e.Raw = vLog
			cb, err := p.(SwapMeetProcessor).ProcessURI(ctx, e)
			if err != nil {
				return nil, fmt.Errorf("processing URI: %w", err)
			}

			return cb, nil

		}
		return func(*ent.Tx) error { return nil }, nil
	}
}

func (h *BaseSwapMeetProcessor) UnpackLog(out interface{}, event string, log types.Log) error {
	if len(log.Data) > 0 {
		if err := h.ABI.UnpackIntoInterface(out, event, log.Data); err != nil {
			return err
		}
	}
	var indexed abi.Arguments
	for _, arg := range h.ABI.Events[event].Inputs {
		if arg.Indexed {
			indexed = append(indexed, arg)
		}
	}
	return abi.ParseTopics(out, indexed, log.Topics[1:])
}

func (h *BaseSwapMeetProcessor) Initialize(ctx context.Context, start uint64, tx *ent.Tx) error {
	return nil
}

func (h *BaseSwapMeetProcessor) ProcessApprovalForAll(ctx context.Context, e SwapMeetApprovalForAll) (func(tx *ent.Tx) error, error) {
	return func(tx *ent.Tx) error { return nil }, nil
}

func (h *BaseSwapMeetProcessor) ProcessOwnershipTransferred(ctx context.Context, e SwapMeetOwnershipTransferred) (func(tx *ent.Tx) error, error) {
	return func(tx *ent.Tx) error { return nil }, nil
}

func (h *BaseSwapMeetProcessor) ProcessSetRle(ctx context.Context, e SwapMeetSetRle) (func(tx *ent.Tx) error, error) {
	return func(tx *ent.Tx) error { return nil }, nil
}

func (h *BaseSwapMeetProcessor) ProcessTransferBatch(ctx context.Context, e SwapMeetTransferBatch) (func(tx *ent.Tx) error, error) {
	return func(tx *ent.Tx) error { return nil }, nil
}

func (h *BaseSwapMeetProcessor) ProcessTransferSingle(ctx context.Context, e SwapMeetTransferSingle) (func(tx *ent.Tx) error, error) {
	return func(tx *ent.Tx) error { return nil }, nil
}

func (h *BaseSwapMeetProcessor) ProcessURI(ctx context.Context, e SwapMeetURI) (func(tx *ent.Tx) error, error) {
	return func(tx *ent.Tx) error { return nil }, nil
}

func (h *BaseSwapMeetProcessor) mustEmbedBaseSwapMeetProcessor() {}
