// Code generated by entc, DO NOT EDIT.

package wallet

const (
	// Label holds the string label denoting the wallet type in the database.
	Label = "wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPaper holds the string denoting the paper field in the database.
	FieldPaper = "paper"
	// EdgeDopes holds the string denoting the dopes edge name in mutations.
	EdgeDopes = "dopes"
	// Table holds the table name of the wallet in the database.
	Table = "wallets"
	// DopesTable is the table that holds the dopes relation/edge.
	DopesTable = "dopes"
	// DopesInverseTable is the table name for the Dope entity.
	// It exists in this package in order to avoid circular dependency with the "dope" package.
	DopesInverseTable = "dopes"
	// DopesColumn is the table column denoting the dopes relation/edge.
	DopesColumn = "wallet_dopes"
)

// Columns holds all SQL columns for wallet fields.
var Columns = []string{
	FieldID,
	FieldPaper,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
