/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CrossDomainMessenger,
  CrossDomainMessengerInterface,
} from "../CrossDomainMessenger";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_message",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_messageNonce",
        type: "uint256",
      },
    ],
    name: "relayMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class CrossDomainMessenger__factory {
  static readonly abi = _abi;
  static createInterface(): CrossDomainMessengerInterface {
    return new utils.Interface(_abi) as CrossDomainMessengerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CrossDomainMessenger {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CrossDomainMessenger;
  }
}
