[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', 'uniswap-v3-periphery/=lib/uniswap-v3-periphery/contracts/']
optimizer = true
optimizer_runs = 2000000000

# See more config options https://github.com/gakonst/foundry/tree/master/config
