name: web
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Write .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_S3_ID: ${{ secrets.S3_ID }}
          envkey_S3_SECRET: ${{ secrets.S3_SECRET }}
          envkey_SECRET_WORD: ${{ secrets.SECRET_WORD }}
      - name: install
        run: yarn
      - name: build
        run: yarn web build

